# Generated by Django 4.2.7 on 2025-10-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('min_spins', models.IntegerField(help_text='Minimum spins required to be eligible for this award.')),
                ('image', models.ImageField(upload_to='awards/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(help_text='Each participant must have a unique email.', max_length=254, unique=True)),
                ('last_spin', models.DateTimeField(blank=True, null=True)),
                ('last_extra_spin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='A unique slug for the roulette URL.', max_length=255, unique=True)),
                ('logo', models.ImageField(upload_to='roulette/logos/')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('bottom_text', models.TextField(blank=True, default='')),
                ('bg_image', models.ImageField(upload_to='roulette/backgrounds/')),
                ('current_spins', models.IntegerField(default=0, help_text='Tracks the total number of spins for this roulette.')),
                ('wrong_icon', models.ImageField(upload_to='roulette/icons/')),
                ('message_error_no_spin', models.CharField(max_length=255)),
                ('message_lose_lose', models.CharField(max_length=255)),
                ('message_win', models.CharField(max_length=255)),
                ('color_spin_1', models.CharField(help_text='Hex color code, e.g., #FFFFFF', max_length=7)),
                ('color_spin_2', models.CharField(help_text='Hex color code, e.g., #FFFFFF', max_length=7)),
                ('color_spin_3', models.CharField(help_text='Hex color code, e.g., #FFFFFF', max_length=7)),
                ('color_spin_4', models.CharField(help_text='Hex color code, e.g., #FFFFFF', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the award was won.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulette.award')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulette.participant')),
            ],
            options={
                'verbose_name': "Participant's Award",
                'verbose_name_plural': "Participant's Awards",
                'unique_together': {('participant', 'award')},
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='awards',
            field=models.ManyToManyField(related_name='winners', through='roulette.ParticipantAward', to='roulette.award'),
        ),
        migrations.AddField(
            model_name='participant',
            name='roulette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='roulette.roulette'),
        ),
        migrations.AddField(
            model_name='award',
            name='roulette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='roulette.roulette'),
        ),
    ]
