# Generated by Django 4.2.7 on 2025-10-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testother',
            options={'verbose_name': 'Prueba Tipo', 'verbose_name_plural': 'Pruebas Tipos'},
        ),
        migrations.AddField(
            model_name='test',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
