# Generated by Django 4.2.7 on 2025-10-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantaward',
            unique_together=set(),
        ),
    ]
