# Generated by Django 4.2.7 on 2025-10-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0002_alter_participantaward_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'Premio', 'verbose_name_plural': 'Premios'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterModelOptions(
            name='participantaward',
            options={'verbose_name': 'Premio de Participante', 'verbose_name_plural': 'Premios de Participantes'},
        ),
        migrations.AlterModelOptions(
            name='roulette',
            options={'verbose_name': 'Ruleta', 'verbose_name_plural': 'Rouletas'},
        ),
    ]
