# Generated by Django 4.2.7 on 2025-10-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0002_alter_testother_options_test_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='counter',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
