# Generated by Django 4.2.7 on 2025-10-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0003_alter_award_options_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='active',
            field=models.BooleanField(default=True, help_text='Si está activo, el premio se mostrará en la ruleta.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='award',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='award',
            name='image',
            field=models.ImageField(upload_to='awards/', verbose_name='Imagen del premio'),
        ),
        migrations.AlterField(
            model_name='award',
            name='min_spins',
            field=models.IntegerField(help_text='Mínimo de giros requeridos para ser elegible para este premio.', verbose_name='Mínimo de giros'),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='award',
            name='roulette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='roulette.roulette', verbose_name='Ruleta'),
        ),
        migrations.AlterField(
            model_name='award',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='awards',
            field=models.ManyToManyField(related_name='winners', through='roulette.ParticipantAward', to='roulette.award', verbose_name='Premios'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_extra_spin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último giro extra'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_spin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último giro'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='roulette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='roulette.roulette', verbose_name='Ruleta'),
        ),
        migrations.AlterField(
            model_name='participantaward',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulette.award', verbose_name='Premio'),
        ),
        migrations.AlterField(
            model_name='participantaward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de cuando el premio fue ganado.'),
        ),
        migrations.AlterField(
            model_name='participantaward',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulette.participant', verbose_name='Participante'),
        ),
        migrations.AlterField(
            model_name='participantaward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='bg_image',
            field=models.ImageField(upload_to='roulette/backgrounds/', verbose_name='Imagen de fondo'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='bottom_text',
            field=models.TextField(blank=True, default='', verbose_name='Texto inferior'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='color_spin_1',
            field=models.CharField(help_text='Hex color code, e.g., #FFFFFF', max_length=7, verbose_name='Color 1'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='color_spin_2',
            field=models.CharField(help_text='Hex color code, e.g., #FFFFFF', max_length=7, verbose_name='Color 2'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='color_spin_3',
            field=models.CharField(help_text='Hex color code, e.g., #FFFFFF', max_length=7, verbose_name='Color 3'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='color_spin_4',
            field=models.CharField(help_text='Hex color code, e.g., #FFFFFF', max_length=7, verbose_name='Color 4'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='current_spins',
            field=models.IntegerField(default=0, help_text='Total de giros realizados en la ruleta. No editar manualmente.', verbose_name='Total de giros'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='logo',
            field=models.ImageField(upload_to='roulette/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='message_error_no_spin',
            field=models.CharField(max_length=255, verbose_name='Mensaje de error (sin mas giros)'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='message_lose_lose',
            field=models.CharField(max_length=255, verbose_name='Mensaje de error (perdió)'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='message_win',
            field=models.CharField(max_length=255, verbose_name='Mensaje de felicitaciones (ganó)'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='slug',
            field=models.SlugField(help_text='url autogenerada para la ruleta.', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='wrong_icon',
            field=models.ImageField(upload_to='roulette/icons/', verbose_name='Icono de error (sin premio)'),
        ),
    ]
