# Generated by Django 4.2.7 on 2025-10-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0003_alter_test_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
