# Generated by Django 4.2.7 on 2025-10-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0004_alter_award_active_alter_award_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participantaward',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
