# Generated by Django 4.2.7 on 2025-10-13 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0005_client_test_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulette.client'),
        ),
    ]
