# Generated by Django 4.2.7 on 2025-10-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0005_alter_award_id_alter_participant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
