# Generated by Django 4.2.7 on 2025-10-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0006_alter_participant_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_extra_spin',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_spin',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='roulette',
        ),
        migrations.CreateModel(
            name='ParticipantSpin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('last_spin', models.DateTimeField(blank=True, null=True, verbose_name='Último giro')),
                ('last_extra_spin', models.DateTimeField(blank=True, null=True, verbose_name='Último giro extra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulette.participant', verbose_name='Participante')),
                ('roulette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulette.roulette', verbose_name='Ruleta')),
            ],
            options={
                'verbose_name': 'Giro de Participante',
                'verbose_name_plural': 'Giros de Participantes',
            },
        ),
    ]
