# Generated by Django 4.2.7 on 2025-10-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0007_remove_participant_awards_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roulette',
            old_name='message_lose_lose',
            new_name='message_lose',
        ),
        migrations.RenameField(
            model_name='roulette',
            old_name='message_error_no_spin',
            new_name='message_no_spins',
        ),
    ]
