# Generated by Django 4.2.7 on 2025-10-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0008_rename_message_lose_lose_roulette_message_lose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantspin',
            name='last_extra_spin',
        ),
        migrations.RemoveField(
            model_name='participantspin',
            name='last_spin',
        ),
        migrations.RemoveField(
            model_name='roulette',
            name='current_spins',
        ),
        migrations.AddField(
            model_name='participantspin',
            name='is_extra_spin',
            field=models.BooleanField(default=False, verbose_name='Es giro extra (ads)'),
        ),
        migrations.AddField(
            model_name='roulette',
            name='spins_ads_limit',
            field=models.IntegerField(default=0, help_text='e.g. 2 (girar 2 veces extra, en base al Espacio entre giros)', verbose_name='Límite de giros (ads)'),
        ),
        migrations.AddField(
            model_name='roulette',
            name='spins_space_hours',
            field=models.IntegerField(default=0, help_text='e.g. 2 (girar una vez cada 2 horas)', verbose_name='Espacio entre giros (horas)'),
        ),
    ]
