# Generated by Django 4.2.7 on 2025-10-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0009_remove_participantspin_last_extra_spin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roulette',
            name='spins_space_hours',
            field=models.FloatField(default=0, help_text='e.g. 2 (girar una vez cada 2 horas)', verbose_name='Espacio entre giros (horas)'),
        ),
    ]
