# Generated by Django 4.2.7 on 2025-10-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0010_alter_roulette_spins_space_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='spins_counter',
            field=models.IntegerField(default=0, help_text='Total de giros realizados en la ruleta desde último premio ganado. No editar manualmente.', verbose_name='Contador de giros'),
        ),
    ]
