# Generated by Django 4.2.7 on 2025-10-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0011_roulette_spins_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='google_ads_code',
            field=models.TextField(blank=True, default='', verbose_name='Código compelto de Google Ads'),
        ),
    ]
